version: '3'

services:
    pmcaptcha:
        container_name: pmcaptcha
        build: .
        ports:
            - "5000:5000"
        restart: unless-stopped
        volumes:
            - ./images:/app/images
